ci: fix registry auth error
because openshift-ci is failing with hidden error
```
Error: logging into "image-registry.openshift-image-registry.svc:5000": invalid username/password
```
and buildindeximage pod to status ImagePullBackOff

Signed-off-by: karampok <karampok@gmail.com>